---
title: "Fig4_BARe-seq_v1"
author: "FL"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
require(vroom)
require(data.table)
require(ggplot2)
require(gridExtra)
require(pheatmap)
require(stringr)
require(dplyr)

STARR <- fread("/groups/stark/lorbeer/Libraries/STARR_TWIST_metadata_v2_corrected_withOhler.txt")
colnames(STARR)[42:52] <- c("ETS", "SREBP", "Trl", "AP1", "GATA", "twist", "Ohler6", "Ohler8", "Dref", "Ohler7", "Ohler1")
STARR[, seq_ID := sub("_[^_]+$", "", ID)]

main_mots <- c("ETS", "SREBP", "Trl", "AP1", "GATA", "twist", "Ohler6", "Dref", "Ohler7", "Ohler1")

```


```{r, echo=FALSE}

TF_motifs <- main_mots
names(TF_motifs) <- main_mots

enhancers$main_mots <- ""
for (x in names(TF_motifs)){
  column <- enhancers[[x]]  # Use [[ ]] for column extraction
  enhancers$main_mots <- paste0(enhancers$main_mots, ifelse(column == 0, "", paste0(x, "-")))
}

require(ggupset)
#enhancers_selected$categories_list <- lapply(strsplit(promoter_selected$main_mots, "-"), unlist(unlist))
#prom_selected_test <- cbind(lapply(strsplit(enhancers_selected$main_mots, "-"), unlist(unlist)), enhancers_selected)
#test2 <- cbind(promoter_selected, lapply(prom_selected_test$categories_list, unlist))

enhancers$V2 <- lapply(strsplit(enhancers$main_mots, "-"), unlist(unlist))


```


```{r, echo = FALSE}
#count how many lines have which motif
#https://r-graph-gallery.com/128-ring-or-donut-plot.html
#https://rforpoliticalscience.com/2020/07/26/make-wes-anderson-themed-graphs-with-wesanderson-package-in-r/ 
TF_freq <- as.data.frame(table(unlist(lapply(strsplit(enhancers$main_mots, "-"), unlist(unlist)))))

#donut chart
# Compute percentages
TF_freq$fraction = TF_freq$Freq / sum(TF_freq$Freq)

# Compute the cumulative percentages (top of each rectangle)
TF_freq$ymax = cumsum(TF_freq$fraction)

# Compute the bottom of each rectangle
TF_freq$ymin = c(0, head(TF_freq$ymax, n=-1))

motif_cols <- c(
  "ETS" = "darkorange",
  "GATA" = "red",
  "AP1" = "orange", 
  "SREBP" = "darkred", 
  "Trl" = "pink",
  "twist" = "pink3",
  "Ohler6" = "lightblue",  
  "Ohler7" = "turquoise4",
  "Ohler1" = "darkblue",
  "Dref" = "blue"
)

# Set plotting order manually
plot_order <- c("ETS", "GATA", "AP1", "SREBP", "Trl", "twist", "Ohler6", "Ohler7", "Ohler1", "Dref")

TF_freq <- TF_freq %>%
  mutate(Var1 = factor(Var1, levels = plot_order)) %>%
  arrange(Var1) %>%
  mutate(
    ymax = cumsum(Freq),
    ymin = lag(ymax, default = 0),
    label_pos = (ymax + ymin) / 2
  )

ggplot(TF_freq, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = Var1)) +
  geom_rect() +
  geom_text(
    aes(x = 3.5, y = label_pos, label = Freq),
    color = "white",
    size = 4
  ) +
  scale_fill_manual(values = motif_cols, breaks = plot_order) +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void()

print(TF_freq)


```
##log2FC of medians of groups 
```{R, echo = FALSE}




```

##Multivariate analysis of enhancer motifs
```{R, echo = FALSE}




```

##Meta analysis 
```{R, echo = FALSE}




```

## motif PWM 
```{R, echo = FALSE}
data_30_annotated <- read.delim("/groups/stark/lorbeer/Burst_params_DG/Parameters_E57_v3/data_30_annotated_muKS.txt")



```
