---
title: "Fig3_Global_comparisons"
author: "FL"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(data.table)
require(dplyr)
require(ggplot2)
require(readxl)
```

## Comparison of burst parameters between STAP and STARR-seq
We want to figure out how promoters and enhancers shape burst parameters 
1) Loading both data sets and merging them to have one data set "dat" that contains all the information 
2) Loading the mu threshold excel file (March 2026)

```{r, echo = FALSE}
#loading data that is required for Fig 2
#STAP seq
#STAP_annotated <- readRDS("/groups/stark/lorbeer/Burst_params_DG/STAP_March2025_pools/STAP_annotated_Fig1_compiled.rds")
STAP_annotated <- readRDS("/groups/stark/lorbeer/Burst_params_DG/STAP_March2025_pools/STAP_annotated_Fig1_compiled_v2.rds")
#STARR seq
STARR_annotated <- readRDS("/groups/stark/lorbeer/Burst_params_DG/STARR_March2025_pools/STARR_annotated_log2FC.rds")

columns_to_use <- c("seq_ID", "sample", "condition", "experiment", "library","rep", "bfreq", "bsize", "exp", "log2FoldChange", "full_prec2", "high_mu", "filter1", "filter2", "bfreq.thres", "bsize.thres", "KS_pval")

dat <- rbind(STAP_annotated[, columns_to_use, with = FALSE], 
STARR_annotated[, columns_to_use, with = FALSE])

mu_thresholds <- read_xlsx("/groups/stark/lorbeer/Burst_params_DG/mu_thresholds_v2_Reyna.xlsx")
dat <- merge(dat, mu_thresholds, by = c("sample", "experiment", "library"), all.x = TRUE)
dat[, high_mu := exp >= mu_threshold_nofilter]

```

##all data sets in one plot

```{r, echo = FALSE}

dat %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE,
         sample %in% c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2",
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6")) %>%
  mutate(sample = factor(sample, levels = c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2",
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6"))) %>%
  ggplot(aes(y = log10(exp), x = log10(bfreq))) +
#  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "lm", formula = y ~ x, se = TRUE, na.rm = TRUE, alpha = 0.2
  ) +
  #scale_color_manual(values = c("#97a6c4","#384860","#384860","#d8a6a6" , "#a00000", "#a00000")) +
  #scale_fill_manual(values = c("#97a6c4","#384860","#384860", "#d8a6a6", "#a00000", "#a00000")) +
    scale_color_manual(values = c("#1E88E5","#8CCBFF","#0B3D91","#F2994A", "#F7D154", "#B87400")) +
  scale_fill_manual(values = c("#1E88E5","#8CCBFF","#0B3D91", "#F2994A", "#F7D154", "#B87400")) +
  coord_cartesian(ylim = c(-1.5, 1.25), xlim = c(-2, 0.5)) +
  theme_classic(base_size = 15)+ 
  ggtitle("KS p_val > 0.01 & mu")
#+ theme(legend.position="none")

dat %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE,
         sample %in% c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2",
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6")) %>%
  mutate(sample = factor(sample, levels = c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2",
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6"))) %>%
  ggplot(aes(y = log10(exp), x = log10(bsize))) +
#  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "lm", formula = y ~ x, se = TRUE, na.rm = TRUE, alpha = 0.2
  ) +
    scale_color_manual(values = c("#1E88E5","#8CCBFF","#0B3D91","#F2994A", "#F7D154", "#B87400")) +
  scale_fill_manual(values = c("#1E88E5","#8CCBFF","#0B3D91","#F2994A", "#F7D154", "#B87400")) +
  coord_cartesian(ylim = c(-1.25, 1.25), xlim = c(-1.5, 1.5)) +
  theme_classic(base_size = 15)+ theme(legend.position="none")+ 
  ggtitle("KS_pval > 0.01 & mu")



```


```{r, echo = FALSE}
dat_filt <- dat %>%
  filter(  KS_pval > 0.01, 
         high_mu == TRUE,  sample %in% c(
      "libFL008_E28_RT2_pooledby2",
      "libFL016_E38_e325_pooledby2",
      "libFL017_E38_e339_pooledby2",
      "libFL010_E24_rg_pooledby2", 
      "libFL013_E39_p309_pooledby4", 
      "libFL014_E39_p319_pooledby6"
    )
  ) %>%
  mutate(sample = factor(
    sample,
    levels = c(
      "libFL008_E28_RT2_pooledby2",
      "libFL016_E38_e325_pooledby2",
      "libFL017_E38_e339_pooledby2",
      "libFL010_E24_rg_pooledby2", 
      "libFL013_E39_p309_pooledby4", 
      "libFL014_E39_p319_pooledby6"
    )
  ))
summarize_lm <- function(df, y_var) {
  df %>%
    mutate(x = log10(exp), y = log10(.data[[y_var]])) %>%
    filter(is.finite(x), is.finite(y)) %>%
    group_by(sample) %>%
    do({
      m <- lm(y ~ x, data = .)
      tibble(
        intercept   = coef(m)[["(Intercept)"]],
        slope       = coef(m)[["x"]],
        intercept_se= coef(summary(m))[1, "Std. Error"],
        slope_se    = coef(summary(m))[2, "Std. Error"],
        slope_p     = coef(summary(m))[2, "Pr(>|t|)"],
        r2          = summary(m)$r.squared,
        adj_r2      = summary(m)$adj.r.squared,
        sigma       = summary(m)$sigma,
        nobs        = length(m$fitted.values)
      )
    }) %>%
    ungroup() %>%
    arrange(sample)
}

bfreq_stats_min <- summarize_lm(dat_filt, "bfreq")
bsize_stats_min <- summarize_lm(dat_filt, "bsize")

#library(scales)

palette_vals <-c("#1E88E5","#8CCBFF","#0B3D91", "#F2994A", "#F7D154", "#B87400")

fmt_p <- function(p) {
  case_when(
    is.na(p)           ~ "p = NA",
    p < 0.0001          ~ "p < 0.0001",
    p < 0.001          ~ "p < 0.001",
    TRUE               ~ paste0("p = ", scales::number(p, accuracy = 0.001))
  )
}

plot_slopes <- function(stats_df, title_text) {
  # Determine y limits to comfortably accommodate error bars and labels
  ymax <- max(stats_df$slope + stats_df$slope_se, na.rm = TRUE)
  ymin <- min(stats_df$slope - stats_df$slope_se, na.rm = TRUE)
  
  # Vertical offset for p-value labels (adjust as needed)
  label_offset <- 0.05 * (ymax - ymin)
  
  ggplot(stats_df, aes(x = sample, y = slope, fill = sample)) +
    geom_bar(stat = "identity", width = 0.8) +
    geom_errorbar(aes(ymin = slope - slope_se, ymax = slope + slope_se),
                  width = 0.2) +
    geom_text(aes(y = slope + slope_se + label_offset, label = fmt_p(slope_p)),
              size = 4, vjust = 0) +
    scale_fill_manual(values = palette_vals, guide = "none") +
    labs(
      title = title_text,
      x = "Sample",
      y = "Slope (log10 exp vs log10 response)"
    ) +
    theme_classic(base_size = 15) +
    theme(
      axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1)
    )
}

# Plots
plot_slopes(bfreq_stats_min, "Slope of log10(exp) ~ log10(bfreq) by Sample (KS pval & mu)")
plot_slopes(bsize_stats_min, "Slope of log10(exp) ~log10(bsize) by Sample (KS pval & mu")

# pdf("/groups/stark/lorbeer/Burst_params_DG/exp_v_bfreq_slope_5x5.pdf", width = 5, height = 5)
# plot_slopes(bfreq_stats_min, "Slope of log10(exp) ~log10(bfreq) by Sample (KS pval & mu")
# dev.off()

# pdf("/groups/stark/lorbeer/Burst_params_DG/exp_v_bsize_slope_5x5.pdf", width = 5, height = 5)
# plot_slopes(bsize_stats_min, "Slope of log10(exp) ~log10(bsize) by Sample (KS pval & mu")
# dev.off()

```
## promoters 

```{r, echo = FALSE}

promoter_bfreq <- dat %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
         sample %in% c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2")) %>% 
  mutate(sample = factor(sample, levels = c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2"))) %>% 
  ggplot(aes(y = log10(exp), x = log10(bfreq))) +
#  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "lm", formula = y ~ x, se = TRUE, na.rm = TRUE, alpha = 0.2
  ) +
  #scale_color_manual(values = c("#97a6c4","#384860","#384860","#d8a6a6" , "#a00000", "#a00000")) +
  #scale_fill_manual(values = c("#97a6c4","#384860","#384860", "#d8a6a6", "#a00000", "#a00000")) +
    scale_color_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  scale_fill_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  coord_cartesian(ylim = c(-1.5, 1.25), xlim = c(-2, 0.5)) +
  theme_classic(base_size = 15)+ theme(legend.position="none")+ 
  ggtitle("promoter KS pval > 0.01 & high mu")

promoter_bfreq

promoter_bsize <- dat %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
         sample %in% c(
                  "libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2")) %>%
  mutate(sample = factor(sample, levels = c(
                  "libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2"))) %>%
  ggplot(aes(y = log10(exp), x = log10(bsize))) +
#  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "lm", formula = y ~ x, se = TRUE, na.rm = TRUE, alpha = 0.2
  ) +
    scale_color_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  scale_fill_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  coord_cartesian(ylim = c(-1.25, 1.25), xlim = c(-1.5, 1.5)) +
  theme_classic(base_size = 15)+ theme(legend.position="none")+ 
  ggtitle("promoter KS pval > 0.01 & high mu")
promoter_bsize


# pdf("/groups/stark/lorbeer/Burst_params_DG/exp_v_bfreq_promoters_5x5.pdf", width = 5, height = 5)
# print(promoter_bfreq)
# dev.off()

# pdf("/groups/stark/lorbeer/Burst_params_DG/exp_v_bsize_promoters_5x5.pdf", width = 5, height = 5)
# print(promoter_bsize)
# dev.off()

```


```{r, echo = FALSE}

enhancer_bfreq <- dat %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
         sample %in% c("libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6")) %>%
  mutate(sample = factor(sample, levels = c(
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6"))) %>%
  ggplot(aes(y = log10(exp), x = log10(bfreq))) +
#  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "lm", formula = y ~ x, se = TRUE, na.rm = TRUE, alpha = 0.2
  ) +
    scale_color_manual(values = c( "#F2994A", "#F7D154", "#B87400")) +
  scale_fill_manual(values = c( "#F2994A", "#F7D154", "#B87400")) +
  coord_cartesian(ylim = c(-1.5, 1.25), xlim = c(-2, 0.5)) +
  theme_classic(base_size = 15)+ theme(legend.position="none")+ 
  ggtitle("enhancer KS pval > 0.01 & high mu")

enhancer_bfreq

enhancer_bsize <- dat %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
         sample %in% c(
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6")) %>%
  mutate(sample = factor(sample, levels = c(
                  "libFL010_E24_rg_pooledby2", 
                  "libFL013_E39_p309_pooledby4", 
                  "libFL014_E39_p319_pooledby6"))) %>%
  ggplot(aes(y = log10(exp), x = log10(bsize))) +
#  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "lm", formula = y ~ x, se = TRUE, na.rm = TRUE, alpha = 0.2
  ) +
    scale_color_manual(values = c("#F2994A", "#F7D154", "#B87400")) +
  scale_fill_manual(values = c( "#F2994A", "#F7D154", "#B87400")) +
  coord_cartesian(ylim = c(-1.25, 1.25), xlim = c(-1.5, 1.5)) +
  theme_classic(base_size = 15)+ theme(legend.position="none")+ 
  ggtitle("enhancer KS pval > 0.01 & high mu")

enhancer_bsize

# pdf("/groups/stark/lorbeer/Burst_params_DG/exp_v_bfreq_enhancers_5x5.pdf", width = 5, height = 5)
# print(enhancer_bfreq)
# dev.off()

# pdf("/groups/stark/lorbeer/Burst_params_DG/exp_v_bsize_enhancers_5x5.pdf", width = 5, height = 5)
# print(enhancer_bsize)
# dev.off()

```


```{r, echo = FALSE}

STAP_annotated %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
    sample %in% c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2")
  ) %>%
  ggplot(aes(y = log10(exp), x = log10(bsize))) +
  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "loess",
    span = 0.75,     # lower = wigglier, higher = smoother
    se = TRUE,
    alpha = 0.2,
    na.rm = TRUE
  ) +
    scale_color_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  scale_fill_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  theme_classic(base_size = 15)+ 
  ggtitle("loess promoter KS pval > 0.01 & high mu")


STAP_annotated %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
    sample %in% c("libFL008_E28_RT2_pooledby2",
                  "libFL016_E38_e325_pooledby2",
                  "libFL017_E38_e339_pooledby2")
  ) %>%
  ggplot(aes(y = log10(exp), x = log10(bfreq))) +
  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "loess",
    span = 0.75,     # lower = wigglier, higher = smoother
    se = TRUE,
    alpha = 0.2,
    na.rm = TRUE
  ) +
    scale_color_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  scale_fill_manual(values = c("#1E88E5","#8CCBFF","#0B3D91")) +
  theme_classic(base_size = 15)+ 
  ggtitle("loess promoter KS pval > 0.01 & high mu")


STARR_annotated %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
         sample %in% c("libFL010_E24_rg_pooledby2", "libFL013_E39_p309_pooledby4", "libFL014_E39_p319_pooledby6")) %>%
  ggplot(aes(y = log10(exp), x = log10(bsize))) +
  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "loess",
    span = 0.75,     # lower = wigglier, higher = smoother
    se = TRUE,
    alpha = 0.2,
    na.rm = TRUE
  ) +
    scale_color_manual(values = c("#F2994A", "#F7D154", "#B87400")) +
  scale_fill_manual(values = c( "#F2994A", "#F7D154", "#B87400")) +
  theme_classic(base_size = 15)+ 
  ggtitle("loess enhancer KS pval > 0.01 & high mu")


STARR_annotated %>%
  filter(KS_pval > 0.01, 
         high_mu == TRUE, 
         sample %in% c("libFL010_E24_rg_pooledby2", "libFL013_E39_p309_pooledby4", "libFL014_E39_p319_pooledby6")) %>%
  ggplot(aes(y = log10(exp), x = log10(bfreq))) +
  geom_point(aes(color = sample),  alpha = 0.25, na.rm = TRUE) +
  geom_smooth(
    aes(color = sample, fill = sample),
    method = "loess",
    span = 0.75,     # lower = wigglier, higher = smoother
    se = TRUE,
    alpha = 0.2,
    na.rm = TRUE
  ) +
    scale_color_manual(values = c("#F2994A", "#F7D154", "#B87400")) +
  scale_fill_manual(values = c( "#F2994A", "#F7D154", "#B87400")) +
  theme_classic(base_size = 15)+ 
  ggtitle("loess enhancer KS pval > 0.01 & high mu")
```










